name: My Workflow
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'A message to display'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Display message
      run: |
        echo "${{ github.event.inputs.message }}"
